### ISSUE TITLE
[Epic #1.0] Sprint 1st

### ISSUE THREAD

**Issue by khoh123** [khoh123/W1-labs-Manager#1]
**## Sprint 1st**  

**1. 기간**
  - 2017/09/04 ~ 09/15

**2. 대상 항목** 
  
      2-1. W-App**
          - [ ] 온보딩 (기본 프로세스)
          - [ ] 채팅 (기본 기능)
          - [ ] 지도 (동일한 경로)
      2-2. C-App
          - [ ] 주소록 (내 주소록)
          - [ ] 내장소 (학원/학교)

## 3. 사용자 스토리**
    - [ ] 체크

- https://docs.google.com/spreadsheets/d/1f0W2NPHLK3_RV_86rBYEy3Cg8JPCQOcEnt5jbWQwnI4/edit#gid=162084753

**4. 참고 사항**
  
   (1) UI/UX : 해당 항목에 대한 최종 기획서 확인 및 링크 요청
   (2) In Dev : 개발 이슈 사전에 공유 요청
   (3) In QA : 기획/개발 리뷰 요청 테스트 데이터 요청
  
**5. 기타 사항**
  - 없음
